name: delete-packages

on:
  workflow_dispatch:

jobs:
  do-work:
    runs-on: ubuntu-latest
    steps:
      - uses: smartsquaregmbh/delete-old-packages@v0.8.1
        with:
          token: ${{ secrets.GH_PACKAGES_TOKEN }}
          organization: hotio
          type: container
          keep: 0
          names: |
            requestrr
